---
- name: install php-fpm
  become: true
  apt:
    name: php-fpm
    state: present
- name: config nginx and php-fpm
  copy:
    src: default
    dest: /etc/nginx/sites-available/default
- name: Upload info.php
  copy:
    src: "info.php"
    dest: "/var/www/html/info.php"
- name: start nginx
  systemd:
    name: nginx
    state: reloaded
