---
- name: Create MongoDB root user
  mongodb_user:
    login_port: "27017"
    database: "admin"
    name: "{{ mongodb_root_user }}"
    password: "{{ mongodb_root_password }}"
    roles: "root"

- name: Create MongoDB nebo user
  mongodb_user:
    login_user: "{{ mongodb_root_user }}"
    login_password: "{{ mongodb_root_password }}"
    login_port: "27017"
    database: "{{ database_name }}"
    name: "{{ mongodb_nebo_user }}"
    password: "{{ mongodb_nebo_password }}"
    roles:
      - { db: "{{ database_name }}", role: "readWrite" }